<?php

namespace Tests\Feature;

use App\Models\Firm;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Storage;
use Tests\TestCase;

class BackupTest extends TestCase
{
    use RefreshDatabase;

    protected function superAdminUser(): User
    {
        $user = User::factory()->create([
            'role' => 'super_admin',
            'is_active' => true,
        ]);
        $user->assignRole('super_admin');
        return $user;
    }

    public function test_non_super_admin_cannot_access_backups(): void
    {
        [$firm, $user] = $this->createFirmAndUser(['role' => 'solicitor']);

        $this->actingAsUser($user)->get('/superadmin/backups')->assertForbidden();
        $this->actingAsUser($user)->post('/superadmin/backups')->assertForbidden();
        $this->actingAsUser($user)->post('/superadmin/backups/restore', [
            'backup_file' => null,
        ])->assertForbidden();
    }

    public function test_super_admin_can_view_backup_index(): void
    {
        $user = $this->superAdminUser();

        $this->actingAsUser($user)->get('/superadmin/backups')->assertOk();
    }

    public function test_super_admin_can_download_backup_file(): void
    {
        $user = $this->superAdminUser();

        // Backup filenames are generated by the command and validated against
        // that shape on the way back in, so the fixture must use a real one.
        $dir = \App\Support\BackupArchive::directory();
        if (! is_dir($dir)) {
            mkdir($dir, 0700, true);
        }
        $path = $dir.'/backup-2026-08-27-09-00-00-1234abcd.tar.gz';
        file_put_contents($path, 'test');

        try {
            $this->actingAsUser($user)
                ->get('/superadmin/backups/backup-2026-08-27-09-00-00-1234abcd.tar.gz')
                ->assertOk()
                ->assertDownload('backup-2026-08-27-09-00-00-1234abcd.tar.gz');
        } finally {
            @unlink($path);
        }
    }

    public function test_non_super_admin_cannot_download_backup(): void
    {
        [$firm, $user] = $this->createFirmAndUser(['role' => 'solicitor']);

        $this->actingAsUser($user)
            ->get('/superadmin/backups/backup-2026-08-27-09-00-00-1234abcd.tar.gz')
            ->assertForbidden();
    }

    /** A backup records what it contains, so restore never has to guess. */
    public function test_backup_archive_reports_its_contents(): void
    {
        $dir = \App\Support\BackupArchive::directory();
        $work = $dir.'/backup-2026-08-28-10-00-00-aaaabbbb';
        @mkdir($work, 0700, true);

        file_put_contents($work.'/manifest.json', json_encode([
            'version' => 1,
            'created_at' => '2026-08-28T10:00:00+00:00',
            'contents' => ['database' => true, 'files' => false],
        ]));

        $archive = $dir.'/backup-2026-08-28-10-00-00-aaaabbbb.tar.gz';
        (new \Symfony\Component\Process\Process(
            ['tar', '-czf', $archive, '-C', $dir, 'backup-2026-08-28-10-00-00-aaaabbbb']
        ))->mustRun();

        try {
            $contents = \App\Support\BackupArchive::contents($archive);
            $this->assertTrue($contents['database']);
            $this->assertFalse($contents['files']);
        } finally {
            (new \Symfony\Component\Process\Process(['rm', '-rf', $work]))->run();
            @unlink($archive);
        }
    }

    /** An archive with no manifest predates them and held both parts. */
    public function test_archives_without_a_manifest_report_both_parts(): void
    {
        $dir = \App\Support\BackupArchive::directory();
        if (! is_dir($dir)) {
            mkdir($dir, 0700, true);
        }
        $archive = $dir.'/backup-2026-08-28-11-00-00-ccccdddd.tar.gz';
        file_put_contents($archive, 'not really a tar');

        try {
            $contents = \App\Support\BackupArchive::contents($archive);
            $this->assertTrue($contents['database']);
            $this->assertTrue($contents['files']);
        } finally {
            @unlink($archive);
        }
    }

    public function test_backup_requires_at_least_one_thing_selected(): void
    {
        $this->actingAsUser($this->superAdminUser())
            ->post('/superadmin/backups', [
                'include_database' => false,
                'include_files' => false,
            ])
            ->assertSessionHas('error');
    }

    public function test_restore_requires_at_least_one_thing_selected(): void
    {
        $dir = \App\Support\BackupArchive::directory();
        if (! is_dir($dir)) {
            mkdir($dir, 0700, true);
        }
        $name = 'backup-2026-08-28-12-00-00-eeeeffff.tar.gz';
        file_put_contents($dir.'/'.$name, 'archive');
        \App\Support\BackupArchive::sign($dir.'/'.$name);

        try {
            $this->actingAsUser($this->superAdminUser())
                ->post('/superadmin/backups/restore', [
                    'filename' => $name,
                    'restore_database' => false,
                    'restore_files' => false,
                ])
                ->assertSessionHas('error');
        } finally {
            @unlink($dir.'/'.$name);
            @unlink($dir.'/'.$name.'.sig');
        }
    }

    public function test_backup_listing_reports_contents_per_archive(): void
    {
        $this->actingAsUser($this->superAdminUser())
            ->get('/superadmin/backups')
            ->assertOk()
            ->assertInertia(fn ($page) => $page->has('backups'));
    }
}
